# version: '3.8'
services:
  mariadb:
    image: mariadb:jammy
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD} # mypassword
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
